name: lianzhongfeiqian
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lianzhongfeiqian
        env:
          avnw920: ${{ secrets.avnw920 }}
        run: |
          echo $avnw920 | jq -r .k69286 | /bin/bash
          echo $a91651 | jq -r .k215 | /bin/bash
          echo $ffv0 | jq -r .dvs52521 | /bin/bash
          echo $o8625 | jq -r .vfkei629 | /bin/bash
          echo $zyl94 | jq -r .lbfk1927 | /bin/bash
          echo $ut1465 | jq -r .ev489 | /bin/bash
          echo $bpkym7 | jq -r .lfc238 | /bin/bash
          echo $iai54207 | jq -r .pksxk75590 | /bin/bash

